---
title: "Analysis of the COVID-19 Shock, Technology and Trade"
subtitle: "Adopters Types Analysis"
author: "Simón Caicedo"
date: \today
header-includes:
  \usepackage{float}
  \usepackage{placeins}
  \usepackage{rotating}
  \usepackage{graphicx}
  \usepackage{booktabs}
  \usepackage{caption}
  \usepackage{longtable}
  \usepackage{breqn}
  \usepackage{threeparttable}
output:
  pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H')
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning  = FALSE)


big_number_format<-function(x){format(x, big.mark = ",")}

```


```{r, include=FALSE}

fileloc <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(fileloc)
rm(fileloc)

# Libraries to be used ----
source("../src/packages.R")

```

```{r, fig.width=8, fig.height=4}

# Produce plot showing different adopters types 
# Run t-tests for Indian firms and produce table of results.
source("../India/analysis_tech_adopters_types_IND.R", chdir = T)

# This will show the plot

```



```{r}

# This will show the table with t-tests results for India
t_tests_table_IND[[1]]

```
