# Packages to be used
library(dplyr)
library(tidyr)
library(arrow)
library(httr)
library(lubridate)
library(haven)
library(forcats)
library(tidytext)
library(ggrepel)
library(ggridges)
library(ggpp)
library(fixest)
library(data.table)
library(modelsummary) # REQUIRES VERSION "1.3.1"
# install.packages("modelsummary", version = "1.3.1")
library(kableExtra)
library(gt)
library(stringr)
library(glue)
library(readr)
library(ggplot2)
library(readxl)
library(penppml)
library(stringi)
library(purrr)
library(powerjoin)
library(collapse)
library(furrr) 
library(stringdist)
library(XML)
library(rvest)
library(fuzzyjoin)
library(ggthemes)
